language: cpp
compiler: g++
script: 
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
before_install:
  - sudo apt-get install autoconf cmake git wget libbz2-dev libcurl4-openssl-dev zlib1g-dev liblzma-dev
install:
  - wget -q https://github.com/samtools/htslib/releases/download/1.11/htslib-1.11.tar.bz2
  - tar -xf htslib-1.11.tar.bz2
  - pushd htslib-1.11 && autoheader && autoconf && ./configure --prefix=/usr/local/ && make && sudo make install && popd
